repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Ensure this version exists
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
  - repo: https://github.com/psf/black
    rev: 21.12b0  # Ensure this version exists
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # Verify and update this version
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Ensure this version exists
    hooks:
      - id: mypy
